name: armagetron # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2.9.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary:  "A Tron clone in 3D."
description: |
   This has been the tagline of Armagetron, since, well, a very long time, and is probably the shortest and most accurate description possible. Tron was an arcade game based on the movie of the same name, release by Disney in 1982. The original game consisted of 4 sub-games, the only one of concern is the 'Light Cycles' one, in which the player uses a left/right joystick to control a 'Light Cycle' which leaves a wall behind it wherever the cycle it goes, turning only at 90 degree angles. The player must then get the AI to crash into their wall while avoiding hitting the AI's own wall themselves. Those were the humble beginnings of Armagetron Advanced's game play, which has now blossomed into 16 player mayhem, with highly advanced AI, network game play, and of course all in a 3D environment.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  armagetron_icon.png
title: Armagetron Advanced

apps:
  armagetron:
    command: armagetron
parts:
  armagetron:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      armagetron: build/
      armagetron.1: man/man1/

architectures:
  - build-on: amd64

